return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "helix",
      delay = 0,
      icons = {
        mappings = false,
      },
      spec = {
        { "<leader>e", group = "Explorer" },
        { "<leader>f", group = "Files" },
        { "<leader>s", group = "Search" },
        { "<leader>g", group = "Git" },
        { "<leader>d", group = "Debug" },
        { "<leader>l", group = "LSP" },
        { "<leader>p", group = "Python" },
        { "<leader>j", group = "Java" },
        { "<leader>t", group = "Terminal / Tasks" },
        { "<leader>q", group = "Session" },
        -- Terminal (see lua/features/terminal.lua)
        { "<leader>tt", desc = "Toggle terminal" },
        { "<leader>tf", desc = "Floating terminal" },
        { "<leader>ta", desc = "Agent terminal" },
        { "<leader>tg", desc = "Git terminal" },
        -- Tasks (see lua/features/tasks.lua)
        { "<leader>tb", desc = "Run build" },
        { "<leader>tr", desc = "Run current file" },
        { "<leader>ts", desc = "Run tests" },
        { "<leader>tp", desc = "Run project" },
        { "<leader>tc", desc = "Clean" },
        -- Git (see lua/features/git.lua)
        { "<leader>gg", desc = "LazyGit" },
        { "<leader>gd", desc = "Diffview" },
        { "<leader>gh", desc = "Preview hunk" },
        { "<leader>gb", desc = "Line blame" },
        { "<leader>gs", desc = "Stage hunk", mode = { "n", "v" } },
        { "<leader>gr", desc = "Reset hunk", mode = { "n", "v" } },
        { "<leader>gu", desc = "Undo stage hunk" },
        { "<leader>gn", desc = "Next hunk" },
        { "<leader>gp", desc = "Previous hunk" },
        { "<leader>gD", desc = "Diff against index" },
        -- Debug (see lua/features/debugger.lua)
        { "<leader>db", desc = "Toggle breakpoint" },
        { "<leader>dB", desc = "Conditional breakpoint" },
        { "<leader>dc", desc = "Continue" },
        { "<leader>di", desc = "Step into" },
        { "<leader>do", desc = "Step over" },
        { "<leader>dO", desc = "Step out" },
        { "<leader>dr", desc = "Open REPL" },
        { "<leader>du", desc = "Toggle UI" },
        { "<leader>dt", desc = "Terminate" },
        { "<leader>dx", desc = "Clear breakpoints" },
        { "<leader>S", desc = "Save" },
        { "<leader>Z", desc = "Quit" },
        { "<leader>c", desc = "Close buffer" },
        { "<leader>:", desc = "Command history" },
        { "<leader><space>", desc = "Buffers" },
        { "<leader>st", desc = "Search TODOs" },
        -- Java (see lua/languages/java-commands.lua)
        { "<leader>T", group = "Testing" },
        { "<leader>Tt", function() require("features.testing").run_nearest() end, desc = "Run nearest test" },
        { "<leader>Tc", function() require("features.testing").run_current_class() end, desc = "Run test class" },
        { "<leader>Tp", function() require("features.testing").run_package() end, desc = "Run package tests" },
        { "<leader>Tm", function() require("features.testing").run_module() end, desc = "Run module tests" },
        { "<leader>Tl", function() require("features.testing").rerun_last() end, desc = "Re-run last test" },
        { "<leader>Td", function() require("features.testing").debug_nearest() end, desc = "Debug nearest test" },
        { "<leader>TD", function() require("features.testing").debug_current_class() end, desc = "Debug test class" },
        { "<leader>W", group = "Workspace" },
        {
          "<leader>Wb",
          function() require("languages.java-commands").build_workspace() end,
          desc = "Build workspace",
        },
        {
          "<leader>Wr",
          function() require("languages.java-commands").reload_workspace() end,
          desc = "Reload workspace",
        },
        {
          "<leader>Ww",
          function() require("languages.java-commands").restart_jdtls() end,
          desc = "Restart jdtls",
        },
        {
          "<leader>Wc",
          function() require("languages.java-commands").clear_workspace_cache() end,
          desc = "Clear workspace cache",
        },
        {
          "<leader>Wl",
          function() require("languages.java-commands").open_workspace_logs() end,
          desc = "Open workspace logs",
        },
        { "<leader>j", group = "Java" },
        { "<leader>jf", desc = "Format Java", mode = { "n", "v" } },
        { "<leader>ji", desc = "Organize imports" },
        { "<leader>jr", desc = "Refactor", mode = { "n", "v" } },
        { "<leader>jc", desc = "Compile project" },
        { "<leader>jp", desc = "Package project" },
        { "<leader>jv", desc = "Verify project" },
        { "<leader>jt", desc = "Run nearest test" },
        { "<leader>jT", desc = "Run test class" },
        { "<leader>jd", desc = "Debug nearest test" },
        { "<leader>jD", desc = "Debug test class" },
        { "<leader>jh", desc = "Call / type hierarchy" },
        { "<leader>jl", desc = "Workspace logs" },
        { "<leader>jw", desc = "Restart workspace" },
        -- LSP (see lua/features/lsp.lua)
        { "gd", desc = "Definition" },
        { "gD", desc = "Declaration" },
        { "gr", desc = "References" },
        { "gi", desc = "Implementation" },
        { "gt", desc = "Type definition" },
        { "K", desc = "Hover documentation" },
        { "<C-k>", desc = "Signature help", mode = "i" },
        { "<leader>lr", desc = "Rename symbol" },
        { "<leader>la", desc = "Code action", mode = { "n", "v" } },
        { "<leader>lf", desc = "Format with LSP", mode = { "n", "v" } },
        { "<leader>ls", desc = "Workspace symbols" },
        { "<leader>ld", desc = "Document symbols" },
      },
    },
  },
}
