return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "helix",
      delay = 0,
      icons = {
        mappings = false,
      },
      spec = {
        { "<leader>e", group = "Explorer" },
        { "<leader>f", group = "Files" },
        { "<leader>s", group = "Search" },
        { "<leader>g", group = "Git" },
        { "<leader>d", group = "Debug" },
        { "<leader>l", group = "LSP" },
        { "<leader>p", group = "Python" },
        { "<leader>j", group = "Java" },
        { "<leader>t", group = "Terminal" },
        { "<leader>q", group = "Session" },
        -- Git (see lua/features/git.lua)
        { "<leader>gg", desc = "LazyGit" },
        { "<leader>gd", desc = "Diffview" },
        { "<leader>gh", desc = "Preview hunk" },
        { "<leader>gb", desc = "Line blame" },
        { "<leader>gs", desc = "Stage hunk", mode = { "n", "v" } },
        { "<leader>gr", desc = "Reset hunk", mode = { "n", "v" } },
        { "<leader>gu", desc = "Undo stage hunk" },
        { "<leader>gn", desc = "Next hunk" },
        { "<leader>gp", desc = "Previous hunk" },
        { "<leader>gD", desc = "Diff against index" },
        { "<leader>W", desc = "Save" },
        { "<leader>Z", desc = "Quit" },
        { "<leader>c", desc = "Close buffer" },
        { "<leader>:", desc = "Command history" },
        { "<leader><space>", desc = "Buffers" },
        { "<leader>st", desc = "Search TODOs" },
        -- LSP (see lua/features/lsp.lua)
        { "gd", desc = "Definition" },
        { "gD", desc = "Declaration" },
        { "gr", desc = "References" },
        { "gi", desc = "Implementation" },
        { "gt", desc = "Type definition" },
        { "K", desc = "Hover documentation" },
        { "<C-k>", desc = "Signature help", mode = "i" },
        { "<leader>lr", desc = "Rename symbol" },
        { "<leader>la", desc = "Code action", mode = { "n", "v" } },
        { "<leader>lf", desc = "Format with LSP", mode = { "n", "v" } },
        { "<leader>ls", desc = "Workspace symbols" },
        { "<leader>ld", desc = "Document symbols" },
      },
    },
  },
}
